language: c

branches:
  only:
    - master

compiler:
  - gcc
  - clang

before_install:
  - pip install --user urllib3[secure] cpp-coveralls
  - sed -i -e '/^import sys$/a import urllib3.contrib.pyopenssl\nurllib3.contrib.pyopenssl.inject_into_urllib3()' `which coveralls`

script:
  - make @enable-gcov=1 test

after_success:
  - coveralls -b . --exclude test --gcov-options '\-lp'

notifications:
  email: false
